name: Build and deploy Node.js project to Azure Function App - student-api-func

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'api'
  NODE_VERSION: '20.x'

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read
      
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies & build
        shell: pwsh
        run: |
          cd $env:AZURE_FUNCTIONAPP_PACKAGE_PATH
          npm install
          npm run build --if-present

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_40464ED23E514CFBA1A187F2BF61193A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_29E18F6F305E43C3B665EB0C4CBF77EE }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_882861DF1DBD48A7A71B05A94283B211 }}

      - name: Deploy to Azure Function
        uses: Azure/functions-action@v1
        with:
          app-name: 'student-api-func'
          slot-name: 'Production'
          package: .

